#!/bin/python3

import math
import os
import random
import re
import sys

def miniMaxSum(arr):
    arr=list(arr)
    arr=sorted(arr)
    minsum=0
    maxsum=0
    p=len(arr)
    for i in range(0,p-1):
        minsum=arr[i]+minsum
    for i in range(1,p):
        maxsum=arr[i]+maxsum
    print(minsum,maxsum)

if __name__ == '__main__':

    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
